export const workExperiences = [
  {
    jobTitle: "SEO Specialist",
    companyName: "MatsMall",
    date: "Apr 2021- Mar 2022",
    responsibilities: [
      "Reviewing and analyzing client sites for areas that can be improved and optimized",
      "Preparing detailed strategy reports",
      "Identifying powerful keywords to drive the most valuable traffic",
      "Improved rankings from page 5 to Top 5 for 10+ high-competition keywords in the interior design niche.",
      "Writing powerful calls-to-action to convert visitors",
      "Filling websites and other content with effective keywords",
      "Writing effective SEO content for blogs, websites, and social media accounts",
      "Developing link building strategies",
      "Analyzing keywords and SEO techniques used by competitors",
      "Keeping updated on both white hat and black hat SEO strategies to avoid staying within search engine guidelines",
      "Compiling and presenting SEO guidelines",
      "Prepare week-over-week reports",
      "Closely collaborate with web development team to ensure SEO best practices are properly followed throughout website content",
    ],
    achievements:
      "Reduce Bounce Rate from 75% to 12 %, Adding more values keywords to the business to rank on it in Google, Bing, Yandex, Improving Google My Business” Local Business”, Increasing the Organic traffic on the website",
  },
  {
    jobTitle: "SEO Specialist",
    companyName: "Reiyada",
    date: "September – October 2021",
    responsibilities: [
      "Conducting keyword research.",
      "Write high-quality blog articles that apply SEO rules and upload them to our website using Rank Math plugin.",
      "Building High-Quality Internal Links, And making A good combination of them in our articles.",
      "performing Competitor's analysis using Ahrefs & SEMrush to find competing domains.",
      "Make reports through Google Data Studio using sources such as Google Analytics, Google Search Console, and google sheets.",
      "using Screaming Frog to perform technical SEO audits.",
      "perform link-building strategies using Ahrefs and Majestic Tools.",
      "Take responsibility for page optimization for search engine marketing",
    ],
    achievements: null,
  },
  {
    jobTitle: "YouTube Specialist",
    companyName: "ENCAFE",
    date: "September – October 2021",
    responsibilities: [
      "Managing ENCAFE’ YouTube Channel and SEO.",
      "Creating monthly detailed reports",
      "Searching for new hashtags & keywords across the different social media platforms.",
      "Meeting the short, medium, and long-term plans discussed with the founder. ",
      "Suggesting new ideas for our YouTube content",
    ],
    achievements:
      "Increase impression by 11%, increase click-through rate by 44%, Increase number of subscribers 96 more than usual, Increase watch time 43.5 more than usual, Increase views 428 more than usual",
  },

  {
    jobTitle: "SEO Specialist",
    companyName: "Try My Price Online",
    date: "June - September 2021",
    responsibilities: [
      "improved organic search rankings from page 5 to Top 5 for 10+ high-competition keywords.",
      "Increase average CTR for transactional keywords.",
      "Stayed up-to-date with the newest SEO guidelines and trends.",
      "Prepared month-over-month reports in an easy-to-read format",
      "Performed competitor analysis.",
    ],
    achievements: null,
  },
  {
    jobTitle: "on-page SEO specialist",
    companyName: "Aqarmap",
    date: "Feb 2021 – June 2021",
    responsibilities: [
      "ensure that all articles fit SEO rules.",
      "distribute targeted keywords within the content.",
      "build high-quality internal links.",
      'use the Related keywords "Synonyms, LSI, Autocomplete" within the content.',
      "create the headings H1, H2, H3, H4, H5, H6.",
      "Write high-quality page descriptions",
      "create the optimum meta titles.",
      "create the optimum meta descriptions.",
      "create a friendly URL.",
    ],
    achievements:
      "Make a successful on-page SEO for many articles in the field of real estate.",
  },
];
